packages:
  - 'packages/*'
overrides:
  happy-dom: 20.8.9
allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  esbuild: true
  sharp: true
  unrs-resolver: true
peerDependencyRules:
  allowedVersions:
    eslint-plugin-import>eslint: ^10.0.0
    eslint-plugin-jsx-a11y>eslint: ^10.0.0
    eslint-plugin-react>eslint: ^10.0.0
