// This file is auto-generated by scripts/generate-themes.ts
// Do not edit this file directly

import { Theme } from '@mui/material/styles'

import * as concrete from './concrete'
import * as mui from './mui'
import * as ywybase from './ywybase'

export const themes: Record<string, Theme> = {
  concrete: concrete.concreteTheme,
  mui: mui.muiTheme,
  ywybase: ywybase.default,
}
