/**
 * @fileoverview Script to auto-generate themes index file from theme definitions.
 *
 * This script scans the src/themes directory for theme definition files and
 * generates an index.ts barrel export that consolidates all themes into a
 * single importable object. This provides a centralized theme registry for
 * dynamic theme switching.
 *
 * @example
 * ```bash
 * # Run the script
 * pnpm run generate:themes
 *
 * # Or run directly
 * npx ts-node scripts/generate-themes.ts
 * ```
 *
 * @requires src/themes directory with .ts theme files
 * @generates src/themes/index.ts
 *
 * @author YwyBase Team
 * @since 1.0.0
 */

import fs from 'node:fs'
import path from 'node:path'

/** Directory containing theme definition files */
const THEMES_DIR = path.join(process.cwd(), 'src', 'themes')

/** Output file path for generated themes index */
const OUTPUT_FILE = path.join(THEMES_DIR, 'index.ts')

/**
 * Generates the themes index file from all theme definitions.
 *
 * This function:
 * 1. Scans src/themes for .ts files (excluding index.ts)
 * 2. Detects the export pattern in each theme file
 * 3. Generates import statements and theme registry object
 * 4. Writes the consolidated index.ts file
 *
 * @async
 * @function generateThemes
 * @returns {Promise<void>} Promise that resolves when index is generated
 * @throws {Error} If themes directory doesn't exist
 *
 * @example
 * ```typescript
 * await generateThemes();
 * console.log('Theme index generated successfully!');
 * ```
 *
 * @remarks
 * **Supported Export Patterns**:
 * - `export const {name}Theme` (e.g., export const muiTheme)
 * - `export default` (default export)
 * - `export const theme` (generic named export)
 *
 * **Generated Structure**:
 * ```typescript
 * export const themes: Record<string, Theme> = {
 *   'mui': mui.muiTheme,
 *   'concrete': concrete.concreteTheme,
 * }
 * ```
 */
async function generateThemes(): Promise<void> {
  console.log('Generating themes index...')

  if (!fs.existsSync(THEMES_DIR)) {
    console.error(`Themes directory not found: ${THEMES_DIR}`)
    process.exit(1)
  }

  const files = fs.readdirSync(THEMES_DIR).filter((file) => file.endsWith('.ts') && file !== 'index.ts')

  const imports: string[] = []
  const themeEntries: string[] = []
  const themeNames: string[] = []

  files.forEach((file) => {
    const name = path.basename(file, '.ts')
    themeNames.push(name)
    // Variable safe name
    const varName = name.replace(/[^a-zA-Z0-9]/g, '_')

    imports.push(`import * as ${varName} from './${name}'`)

    const fileContent = fs.readFileSync(path.join(THEMES_DIR, file), 'utf-8')
    let exportStatement = ''

    if (fileContent.includes(`export const ${name}Theme`)) {
      exportStatement = `${varName}.${name}Theme`
    } else if (fileContent.includes('export default')) {
      exportStatement = `${varName}.default`
    } else if (fileContent.includes('export const theme')) {
      exportStatement = `${varName}.theme`
    } else {
      console.warn(
        `Could not detect theme export for ${file}. expected default export or named export '${name}Theme' or 'theme'`
      )
      // Fallback to previous behavior just in case, or maybe comment it out
      exportStatement = `${varName}.default`
    }

    themeEntries.push(`  '${name}': ${exportStatement},`)
  })

  const content = `// This file is auto-generated by scripts/generate-themes.ts
// Do not edit this file directly

import { Theme } from '@mui/material/styles'

${imports.join('\n')}

export const themes: Record<string, Theme> = {
${themeEntries.join('\n')}
}
`

  fs.writeFileSync(OUTPUT_FILE, content)
  console.log(`Generated ${OUTPUT_FILE} with ${files.length} themes:`)
  themeNames.forEach((name) => console.log(`  - ${name}`))
}

generateThemes().catch((error) => {
  console.error('Failed to generate themes:', error)
  process.exit(1)
})
