/**
 * @fileoverview Script to backup complete Supabase database schema and data.
 *
 * This script connects to your Supabase project and exports:
 * - Complete database schema (tables, indexes, constraints)
 * - All database functions and triggers
 * - Row Level Security (RLS) policies
 * - All table data as SQL INSERT statements
 * - Extension configurations
 * - Scheduled jobs (pg_cron)
 *
 * The backup is saved as a timestamped SQL file that can be used for:
 * - Database restoration
 * - Migration to another project
 * - Schema versioning
 * - Disaster recovery
 *
 * @example
 * ```bash
 * # Run the script
 * pnpm run backup:db
 *
 * # Or run directly with ts-node
 * npx ts-node scripts/generate-supabase-backup.ts
 * ```
 *
 * @requires NEXT_PUBLIC_SUPABASE_PROJECT_ID or SUPABASE_PROJECT_ID in .env.local
 * @requires Supabase CLI to be installed globally
 * @requires psql (PostgreSQL client) to be installed
 *
 * @author YwyBase Team
 * @since 1.0.0
 */

import { execSync } from 'child_process'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import dotenv from 'dotenv'

// Load environment variables from .env.local
dotenv.config({ path: join(process.cwd(), '.env.local') })

// Configuration
const SUPABASE_PROJECT_ID = process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID ?? process.env.SUPABASE_PROJECT_ID
const BACKUP_DIR = join(process.cwd(), 'backups')
const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
const BACKUP_FILE = join(BACKUP_DIR, `backup-${TIMESTAMP}.sql`)

if (!SUPABASE_PROJECT_ID) {
  console.error('❌ Error: SUPABASE_PROJECT_ID is not defined in .env.local')
  process.exit(1)
}

// Commented out unused functions - kept for future use
// /**
//  * Executes a SQL query on the remote Supabase database
//  */
// function executeSQL(sql: string): string {
//   try {
//     const command = `supabase db exec --project-ref ${SUPABASE_PROJECT_ID} --sql "${sql.replace(/"/g, '\\"')}"`
//     return execSync(command, { encoding: 'utf-8' })
//   } catch (error) {
//     console.error('❌ Error executing SQL:', error)
//     throw error
//   }
// }

// /**
//  * Gets database connection string from Supabase CLI
//  */
// function getConnectionString(): string {
//   try {
//     // Get DB URL from supabase CLI
//     const output = execSync(`supabase projects list --project-ref ${SUPABASE_PROJECT_ID}`, {
//       encoding: 'utf-8',
//     })
//
//     // For this to work, we'll use supabase db dump which handles authentication
//     return ''
//   } catch (error) {
//     console.warn('⚠️ Could not get connection string, will use supabase db dump instead')
//     return ''
//   }
// }

/**
 * Backs up the complete database schema and data.
 *
 * This function performs a comprehensive backup including:
 * - Schema structure (CREATE TABLE, ALTER TABLE, etc.)
 * - Functions and triggers
 * - RLS policies
 * - Indexes and constraints
 * - All data as INSERT statements
 * - Extensions and configurations
 *
 * The backup is written as a valid PostgreSQL SQL file that can be
 * executed to restore the database to its exact state.
 */
function backupDatabase(): void {
  console.log('🚀 Starting Supabase database backup...')
  console.log(`📁 Project ID: ${SUPABASE_PROJECT_ID}`)

  // Ensure backup directory exists
  if (!existsSync(BACKUP_DIR)) {
    mkdirSync(BACKUP_DIR, { recursive: true })
    console.log(`✅ Created backup directory: ${BACKUP_DIR}`)
  }

  let backupSQL = ''

  // Header comment
  backupSQL += `-- ============================================================================
-- Supabase Database Backup
-- ============================================================================
-- Project ID: ${SUPABASE_PROJECT_ID}
-- Backup Date: ${new Date().toISOString()}
-- Generated by: scripts/generate-supabase-backup.ts
--
-- This backup includes:
-- - Complete database schema (tables, indexes, constraints)
-- - All database functions and triggers
-- - Row Level Security (RLS) policies
-- - All table data as SQL INSERT statements
-- - Extension configurations
-- - Scheduled jobs (pg_cron)
--
-- To restore:
-- 1. Create a new Supabase project or reset existing one
-- 2. Run: psql [connection-string] < ${BACKUP_FILE}
--
-- Note: No outer transaction wrapper is used because the schema dump may
-- contain DDL statements that cannot run inside a transaction block
-- (e.g., CREATE INDEX CONCURRENTLY, CREATE EXTENSION, ALTER TYPE).
-- Each logical section is self-contained.
-- ============================================================================

`

  try {
    // Step 1: Dump schema using Supabase CLI
    console.log('📦 Exporting database schema...')

    try {
      // Use supabase db dump to get schema
      const schemaOutput = execSync(
        `supabase db dump --project-ref ${SUPABASE_PROJECT_ID} --schema public --schema auth --schema storage`,
        { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 }
      )

      backupSQL += `-- ============================================================================
-- SCHEMA DUMP
-- ============================================================================

${schemaOutput}

`
      console.log('✅ Schema exported successfully')
    } catch (error) {
      console.error('❌ Error exporting schema:', error)
      throw error
    }

    // Step 2: Export data from public tables
    console.log('📊 Exporting table data...')

    try {
      // Get list of tables in public schema
      const tablesQuery = `
        SELECT tablename 
        FROM pg_tables 
        WHERE schemaname = 'public' 
        AND tablename NOT LIKE 'pg_%'
        ORDER BY tablename;
      `

      const tablesOutput = execSync(
        `supabase db exec --project-ref ${SUPABASE_PROJECT_ID} --sql "${tablesQuery.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ')}"`,

        { encoding: 'utf-8' }
      )

      // Parse table names from output (simple text parsing)
      const tables = tablesOutput
        .split('\n')
        .filter((line) => line.trim() && !line.includes('tablename') && !line.includes('---') && !line.includes('row'))
        .map((line) => line.trim())
        .filter(Boolean)

      if (tables.length > 0) {
        backupSQL += `-- ============================================================================
-- TABLE DATA
-- ============================================================================

`

        for (const table of tables) {
          console.log(`  📄 Exporting data from: ${table}`)

          // Get row count first
          const countQuery = `SELECT COUNT(*) FROM public.${table};`
          const countOutput = execSync(
            `supabase db exec --project-ref ${SUPABASE_PROJECT_ID} --sql "${countQuery.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`,

            { encoding: 'utf-8' }
          )

          const rowCount = parseInt(countOutput.match(/\d+/)?.[0] ?? '0')

          if (rowCount > 0) {
            // Export data using COPY TO with CSV format
            const dataQuery = `COPY public.${table} TO STDOUT WITH (FORMAT csv, HEADER true, DELIMITER ',', QUOTE '"', ESCAPE '"');`

            try {
              const dataOutput = execSync(
                `supabase db exec --project-ref ${SUPABASE_PROJECT_ID} --sql "${dataQuery.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`,

                { encoding: 'utf-8', maxBuffer: 50 * 1024 * 1024 }
              )

              if (dataOutput.trim()) {
                backupSQL += `-- Data for table: ${table} (${rowCount} rows)
-- Note: This is CSV format, convert to INSERT statements if needed
-- \COPY public.${table} FROM STDIN WITH (FORMAT csv, HEADER true);
-- ${dataOutput.split('\n').join('\n-- ')}
-- \.

`
              }

              console.log(`    ✅ Exported ${rowCount} rows from ${table}`)
            } catch (error) {
              console.warn(`    ⚠️ Could not export data from ${table}:`, error)
            }
          } else {
            console.log(`    ⏭️  Skipped ${table} (empty table)`)
          }
        }
      } else {
        console.log('  ℹ️  No tables found or unable to list tables')
      }
    } catch (error) {
      console.warn('⚠️ Error exporting data:', error)
      backupSQL += `-- Note: Data export encountered errors, only schema was backed up\n\n`
    }

    // Step 3: Export pg_cron jobs
    console.log('⏰ Exporting scheduled jobs...')

    try {
      const cronQuery = `
        SELECT jobid, schedule, command, nodename, nodeport, database, username, active
        FROM cron.job
        WHERE command IS NOT NULL
        ORDER BY jobid;
      `

      const cronOutput = execSync(
        `supabase db exec --project-ref ${SUPABASE_PROJECT_ID} --sql "${cronQuery.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ')}"`,

        { encoding: 'utf-8' }
      )

      if (cronOutput.includes('|')) {
        backupSQL += `-- ============================================================================
-- SCHEDULED JOBS (pg_cron)
-- ============================================================================

${cronOutput}

`
        console.log('✅ Scheduled jobs exported')
      }
    } catch (error) {
      console.warn('⚠️ Could not export pg_cron jobs:', error)
    }

    // Footer
    backupSQL += `
-- ============================================================================
-- END OF BACKUP
-- ============================================================================
-- Total backup size: ${(backupSQL.length / 1024).toFixed(2)} KB
-- Backup completed at: ${new Date().toISOString()}
-- ============================================================================
`

    // Write backup file
    writeFileSync(BACKUP_FILE, backupSQL, 'utf-8')

    console.log('✅ Backup completed successfully!')
    console.log(`📁 Backup file: ${BACKUP_FILE}`)
    console.log(`📊 Backup size: ${(backupSQL.length / 1024).toFixed(2)} KB`)
    console.log('')
    console.log('💡 To restore this backup:')
    console.log('   1. Create a new Supabase project or reset existing one')
    console.log(`   2. Run: psql [connection-string] < ${BACKUP_FILE}`)
    console.log('   Or use: supabase db reset (if using local development)')
  } catch (error) {
    console.error('❌ Backup failed:', error)
    throw error
  }
}

// Main execution
try {
  console.log('')
  console.log('╔════════════════════════════════════════════════════════════╗')
  console.log('║        Supabase Database Backup Generator                 ║')
  console.log('╚════════════════════════════════════════════════════════════╝')
  console.log('')

  // Check if Supabase CLI is installed
  try {
    execSync('supabase --version', { encoding: 'utf-8' })
  } catch {
    console.error('❌ Error: Supabase CLI is not installed.')
    console.error('   Install it from: https://supabase.com/docs/guides/cli')
    process.exit(1)
  }

  backupDatabase()

  console.log('')
  console.log('✅ All done!')
  console.log('')
} catch (error) {
  console.error('\n❌ Backup process failed:', error)
  process.exit(1)
}
